# Generated by Django 2.2.4 on 2019-11-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aglutinado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_producido', models.CharField(max_length=200)),
                ('forma', models.CharField(max_length=200)),
                ('tipo_espuma', models.CharField(max_length=200)),
                ('num_corrida', models.IntegerField()),
                ('num_block', models.IntegerField()),
                ('tipo_unidad', models.CharField(max_length=200)),
                ('no_lote', models.CharField(max_length=200)),
                ('tipo_defecto', models.CharField(max_length=200)),
                ('ok_ng', models.CharField(max_length=200)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flujo_de_aire', models.IntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_producido', models.CharField(max_length=200)),
                ('forma', models.CharField(max_length=200)),
                ('tipo_espuma', models.CharField(max_length=200)),
                ('num_corrida', models.IntegerField()),
                ('num_block', models.IntegerField()),
                ('tipo_unidad', models.CharField(max_length=200)),
                ('no_lote', models.CharField(max_length=200)),
                ('tipo_defecto', models.CharField(max_length=200)),
                ('ok_ng', models.CharField(max_length=200)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flujo_de_aire', models.IntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cilindro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_producido', models.CharField(max_length=200)),
                ('forma', models.CharField(max_length=200)),
                ('tipo_espuma', models.CharField(max_length=200)),
                ('num_corrida', models.IntegerField()),
                ('num_block', models.IntegerField()),
                ('tipo_unidad', models.CharField(max_length=200)),
                ('no_lote', models.CharField(max_length=200)),
                ('tipo_defecto', models.CharField(max_length=200)),
                ('ok_ng', models.CharField(max_length=200)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flujo_de_aire', models.IntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
