# Generated by Django 2.2.4 on 2019-11-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0002_aglutinado_block_cilindro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aglutinado',
            name='tipo_ajuste',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='block',
            name='tipo_ajuste',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='tipo_ajuste',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='tipo_defecto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='tipo_unidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='tipo_defecto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='tipo_unidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='tipo_defecto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='tipo_unidad',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
