# Generated by Django 2.2.4 on 2019-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0005_auto_20191128_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='aglutinado',
            name='alto_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aglutinado',
            name='ancho_curado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aglutinado',
            name='auth_corte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aglutinado',
            name='densidad_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='aglutinado',
            name='dispobible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aglutinado',
            name='largo_curado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aglutinado',
            name='peso_curado',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='aglutinado',
            name='volumen_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='alto_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='ancho_curado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='auth_corte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='densidad_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='dispobible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='block',
            name='largo_curado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='peso_curado',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='volumen_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='alto_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='ancho_curado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='auth_corte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='densidad_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='dispobible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='largo_curado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='peso_curado',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cilindro',
            name='volumen_curado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='ancho',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='largo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='num_block',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='aglutinado',
            name='tipo_ajuste',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='ancho',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='largo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='num_block',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='tipo_ajuste',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='ancho',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='largo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='num_block',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='tipo_ajuste',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
